header-from: ./.config/header.md

version: ""

formatter: markdown table

name: private-terraform-registry-s3

content: |-
  {{ .Header }}

  # private-terraform-registry-s3

  GitHub: [StratusGrid/private-terraform-registry-s3](https://github.com/StratusGrid/private-terraform-registry-s3)

  This module creates a Terraform Provider Registry in AWS S3 which is accessible from specific IP ranges. For details about Terraform provider registries, please see [Provider Registry Protocol](https://www.terraform.io/internals/provider-registry-protocol).
  An example is also provided below.

  ## Example Usage:

  ```hcl
  {{ include "examples/example1.tfnot" }}
  ```
  
  ---

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  <span style="color:red">Note:</span> Manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml .`

sections:
  show:
    - header
    - resources
    - inputs
    - outputs
    - providers
    - requirements

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: replace
